### ISSUE TITLE
Rule for file too long

### ISSUE THREAD

**Issue by guykisel** [boakley/robotframework-lint#22]
It might be useful to have a warning for files that are more than N lines long. A reasonable default might be 1,000 lines or so. When files get too long they should probably be broken up into multiple shorter files.

**Comment by boakley** [comment]
Yeah, that seems like a good idea. 1000 lines seems like a lot, though. For me, personally, any file over a couple hundred lines is starting to get too long. I'm tempted to pick a lower number, perhaps 300? 400?

**Comment by guykisel** [comment]
Sure, sounds good to me.

**Comment by guykisel** [comment]
Nice! Thanks :smile:
