### ISSUE TITLE
Rules to detect empty tests and keywords

### ISSUE THREAD

**Issue by guykisel** [boakley/robotframework-lint#25]
Tests or keywords containing zero steps should probably be marked as warnings or errors.

**Comment by boakley** [comment]
I've added the rules TooFewTestSteps and TooFewKeywordSteps. These are configurable. The default value is 2 (ie: a test or keyword with zero or one steps will trigger a warning or error). These will be available in the next release (0.6)

See changes 2239021c632fcf5ebf1b482302b7f970e6e55075, c66c59e1e55f260d42d81e45a54eceb8c07293b9, and 684b3a303c2ea1bb6f7657415fd63247bfd57a61 among others.

**Comment by guykisel** [comment]
Nice!
