### ISSUE TITLE
A GeneralRule class rule is not passed an object with a type attribute

### ISSUE THREAD

**Issue by jaloren** [boakley/robotframework-lint#31]
I tried to define a GeneralRule class.  According to the documentation here, this means I will be passed a RobotFile class when the apply method defined in the class is executed.
https://github.com/boakley/robotframework-lint/wiki/The-GeneralRule-class

According to the documentation here, the RobotFile class is super class of SuiteFile and ResourceFile
https://github.com/boakley/robotframework-lint/wiki/The-RobotFile-class

Both the SuiteFile and ResourceFile classes have the type attribute which indicate whether its a resource or test suite. My expectation would be that in a GeneralRule  class, the RobotFile object would have a type attribute that can be inspected to find out if the object is a SuiteFile or ResourceFile.

However, when I access the type attribute, I get the following exception:

SettingTable' object has no attribute 'type'

Here's an example class.

```
class ImportLibraryInResource(GeneralRule):
    severity = ERROR

    def configure(self, jsonfile):
        self.jsonfn = jsonfile
        self.allowed_libs = json.load(open(jsonfile,'r'))

    def apply(self,RobotFile):
        print RobotFile.type
```

**Comment by boakley** [comment]
This will be available in the next release (0.6)
