### ISSUE TITLE
trailing whitespace on line

### ISSUE THREAD

**Issue by djmille1** [boakley/robotframework-lint#37]
I propose a new rule be added to detect instances of trailing whitespace on a line.

**Comment by boakley** [comment]
That's a good idea. Thanks for the suggestion.

**Comment by php-coder** [comment]
I need this as well.

**Comment by boakley** [comment]
This has been fixed in the 1.0 release.

**Comment by php-coder** [comment]
@boakley Thanks!

I see that it doesn't detect trailing spaces in test case names. Is it a bug?
