### ISSUE TITLE
KeywordRule: steps table not contain step, if line contains #

### ISSUE THREAD

**Issue by RiikkaJokinen** [boakley/robotframework-lint#41]
--configure TooFewKeywordSteps:1

This keyword returns TooFewKeywordSteps warning

```
My second keyword
    My first keyword    # call My first keyword
```

When I print out keyword.steps, it returns empy list (= [])

**Comment by RiikkaJokinen** [comment]
Same issue in TooFewTestSteps rule

This test returns TooFewTestSteps warning
```
My test
    Step 1    # step 1
    Step 2    # step 2
    Step 3    # step 2
    Step 4    # step 4

```

**Comment by boakley** [comment]
Thanks for the report! I've found the bug and will try to post a fix soon.
