### ISSUE TITLE
-r seems to call files multiple times depending on depth of folder it is in

### ISSUE THREAD

**Issue by ntdaley** [boakley/robotframework-lint#46]
When the '-r' recursive argument is given on the command line, rflint seems to analyse files more than once.  At least some files appear multiple times in the output.
How often it appears seems to depend on the depth of the folder the file is in.
e.g. below, we can see that files that are immediately under the supplied folder get processed once, files that are a level lower get processed twice, a level below that 4 times, a level below that 8 times, ...

Below is output from a bash script I ran.  Because no two lines have the same number of slashes (the slashes from the file paths), we can see that all files at the same depth show up the same number of times.  The number at the start of each line of output is the number of times that files at that level got repeated.
```
$ rflint -r ./project1/ | grep '^\+' | sort | uniq -c | sort -n |  sed 's/\/[^/]*/\//g ' | uniq 
      1 + .//
      2 + .///
      4 + .////
      8 + ./////

```

Based on those numbers, and looking at the code.  It looks like it is because you are using `os.walk`, which gets all descendant files/folders; but then in the handling for each folder, (`_process_folder`), you are calling os.walk again; which is not necessary, because the top call to `os.walk` has gone down to all descendant folders, not just child folders.

**Comment by boakley** [comment]
Thanks for the report!

**Comment by SCHLUPP42** [comment]
I have experienced the same problem.
Any chance on getting that fixed soon?

**Comment by boakley** [comment]
Yeah, sorry. I have a fix, and just forgot to push it out. I'll try to get
it out soon.

**Comment by SCHLUPP42** [comment]
Any updates on this one?

**Comment by bkhouri** [comment]
@boakley Any ideas on whether pull-request #54 fixes the issue, and if so, when a new release could be done?
