### ISSUE TITLE
Is it possible to ignore (TooFewKeywordSteps) when keyword added with 'No Operation'

### ISSUE THREAD

**Issue by adiralashiva8** [boakley/robotframework-lint#53]
REQUIREMENT: I need a keyword in my test whose implementation will be done in future, so I added keyword with 'No Operation'. 

Example: 

*** Keywords ***
Keyword Name
|    |No Operation

QUESTION: Is it possible to ignore keyword with 'No Operation' in (TooFewKeywordSteps)?

**Comment by boakley** [comment]
At present, no, it's not possible. However, you can certainly write your
own rule that does.

**Comment by Julian88Tex** [comment]
@boakley I vote for a keyword never having too few steps based on our most recent conversation about very readable tests with no variables :-).
