### ISSUE TITLE
rflint does not work with Robot Framework 3.2.0

### ISSUE THREAD

**Issue by hanninen** [boakley/robotframework-lint#73]
When trying to run rflint with Robot Framework 3.2.0 inside a `tox` environment I get the following error.

* `ModuleNotFoundError: No module named 'robot.parsing.txtreader'`

Pinning the `robotframework` version to older than 3.2.0 removes the error.

I checked that Robot Framework no longer has the `robot.parsing.txtreader` module and the whole parser module has gone through quite a big rearrangement / rewriting.

**Comment by ailjushkin** [comment]
For sure, our builds are also failing, quick fix up is constraining with previous release robot-framework==3.1.2

**Comment by bollenn** [comment]
Shall be fixed by https://github.com/boakley/robotframework-lint/pull/74

**Comment by axxyhtrx** [comment]
Please fix this issue

**Comment by freddebacker** [comment]
I'm also impacted by the same issue

**Comment by tgoncuoglu** [comment]
would be nice to have fixed

**Comment by MM2020ops** [comment]
Working with Robot Framework 3.2.0 and the error in rflint is blocking our CI pipeline. Can this be fixed, please?

**Comment by tvanwese** [comment]
Also looking for a fix on this

**Comment by rmilad** [comment]
looking forward for this fix as well

**Comment by biochester** [comment]
hope it will be resolved soon, the fix is really needed (

**Comment by moatazsameh** [comment]
It would be great if its fixed

**Comment by assy94** [comment]
I think it will be great to fix this

**Comment by assy94** [comment]
hopefully to be resolved

**Comment by oakyurek** [comment]
Also need this fixed

**Comment by nick-grout** [comment]
Also needing a fix
