### ISSUE TITLE
ImportError: cannot import name 'FileReader' from 'robot.utils'

### ISSUE THREAD

**Issue by jupe** [boakley/robotframework-lint#76]
I get this kind of error with new version v1.1:
```
ImportError: cannot import name 'FileReader' from 'robot.utils' (/root/project/venv/lib/python3.7/site-packages/robot/utils/__init__.py)
```

Not sure if this related to virtualenv, but previous version worked fine.

**Comment by boakley** [comment]
What version of robot are you using? rflint 1.1 requires robot framework
3.2 (though I realize I didn't specify that anywhere)

**Comment by jupe** [comment]
That was the reason. I was using previous robot version. Please add some notes about that.
