### ISSUE TITLE
InvalidTable,  Unknown table name 'Comments'

### ISSUE THREAD

**Issue by JoaoEnesGoncalves** [boakley/robotframework-lint#79]
having a test case file like
```
*** Setting ***
Library           SeleniumLibrary

*** Comments ***
    blabla bla


*** Keywords ***
kw blabla bla
    blabla bla...


*** Test Cases ***                                
blabla bla
```

When is executed:
`rflint --recursive --ignore all --argumentfile .\rflint.args testdirectory`

was verified:
  - ❌  wrong validation `InvalidTable, Unknown table name 'Comments'`

**notes**
`rflint --version`
1.0

❌  rflint --version returns version 1.0 but pip returns robotframework-lint   1.1

`pip list`
```
Package                        Version
------------------------------ -------
astroid                        2.4.1
autopep8                       1.5.3
colorama                       0.4.3
isort                          4.3.21
lazy-object-proxy              1.4.3
mccabe                         0.6.1
pip                            20.1.1
pycodestyle                    2.6.0
pylint                         2.5.2
PyYAML                         5.3.1
robotframework                 3.1.2
robotframework-lint            1.1
robotframework-pabot           1.8.0
robotframework-seleniumlibrary 4.3.0
robotremoteserver              1.1
selenium                       3.141.0
setuptools                     47.1.1
six                            1.15.0
toml                           0.10.1
typed-ast                      1.4.1
urllib3                        1.25.9
wrapt                          1.12.1
```

**Comment by fperrin** [comment]
Hi @JoaoEnesGoncalves 

rflint version 1.1 knows about the `Comments` table.

If `rflint --version` and `pip list` give two different versions, it means you have 2 different installations and you're not running the correct one when executing `rflint`.

You use a backslash in one of the commands, does that mean you're using Windows? I'm not familiar with Windows, but apparently you can use `where rflint` to find what command is run when you type `rflint`. Compare with the output from `pip show --files robotframework-lint`.

**Comment by JoaoEnesGoncalves** [comment]
thank you for feedback
yes, was a problem on differents users installation versions on Windows10, resolved!
